apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx2
spec:
  containers:
  - image: nginx
    name: nginx2
    resources: 
      requests:
        memory: "0.5Gi"
        cpu: "1m"
      limits:
        memory: "0.5Gi"
        cpu: "1m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  priorityClassName: mediaum
status: {}
