apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: null
  name: basicquota
spec:
  hard:
    configmaps: "1"
    pods: "2"
    services: "3"
    replicationcontrollers: "2"
    resourcequotas: "1" 
    secrets: "5" 
    persistentvolumeclaims: "10"